/**
 * Created by skyeguy on 6/29/17.
 */
function findLiterature(itemType)
{
    if (itemType == "freydicFolkTales")
    {
        reading = [["@@@@@@@@@^^^^ Freydic Folk Tales|@@@@@**The Lady of Frost|___________________________________________________________________________" +
        "______________________||@Once upon a time there lived an old lady named Lekli. Everyone in the town cherished this old lady, for in her youth she " +
        "had acted very kindly to everyone. Even in her old age she found ways to help people. Every now and then a farmer would ask Lekli for tips on how to grow " +
        "her crops, or harvest the best berries. The men consulted her as well, they often saught Lekli's wisdom before leaving for hunts. Some men would ask her if the weather would worsen" +
        " and others would ask if their injuries were too many to hunt, some would even speak with her and try to understand her cryptic riddles believing that she " +
        "would give them good luck.|@After a hearty feast of flame roasted walrus all of the village slept for the night. But Lekli did not. She had pain in her back, as many wise elders " +
        "do. She sat awake that night separating harst seeds from their thick and"], ["^^jagged stalks. It was no mistake that Lekli had not been able to go to sleep that night; the Gods had a " +
        "plan for her. Just after Lekli had finished a tall pile of seeds, her door blew open in the roaring wind. The frosty air pouring into her hut seemed to call to her. Her bones " +
        "rattled as she shivered in the cold, but it wasn't the cold that had her trembling. The cold had always been a comfort to her, it would remind her that life was so much more than" +
        " the trivialities of a human life, and that life could be extinguished just like a lantern in the freezing gusts of wind. What had her trembling this night though, was not just the " +
        "cold, the gods had whispered the truth in her ear. She peeked outside of her hut, in the center of the broken stone courtyard lay a walrus larger than any Lekli had seen in her " +
        "entire life. It was as if it were waiting for her and no one else, for the moment she stepped out into the snow it lifted its head to recognize her. She stood barefoot in the snow" +
        " just beyond the door to her hut, but some how her home seemed so far away. The walrus nodded its head, as if to beckon her towards it. Her feet were compelled. She stepped " +
        "forward with no regard for the frost that was already climbing up her ankles. The great creature lowered its magnificent head, allowing a thick bunch of its un-worldy mane " +
        "to fall into Lekli's wrinkled arms. She"], ["^^held the fur tightly as she stepped delicately up the walruses flipper. Once she was mounted it carried her away into the night." +
        "|@What she saw that night, no one knows, but when she arrived in the morning she was dreadfully ill. Her face was grey as a fish, and she loosed a river of them from her gut as well." +
        " So many fish left from her mouth that morning that everyone who who stood in the entire village was at least knee deep in flopping fish. Lekli lost herself among them. When a man " +
        "tried to reach into the mess and pull her out all he managed to get was a handful of silver hair. As Lekli sunk deeper into the ocean of fish she felt her skin grow hard and her " +
        "limbs come together into flippers. Tusks grew from her face and she slunk away from the village.|@The man who had grabbed Lekli's silver strands of hair went into a rage that night. " +
        "For in his eyes, it was his fault that Lekli had suffered this transformation. If only he had gotten a better grip she would still be human, he told himself so hotly that the ice" +
        " melted from his coat. This man saved the hair. He tied it in a knot and laid it to rest on his alter."], ["^^@Many years passed, and soon the man grew old. He had a son who was now " +
        "hunting age, and a daughter who could un-seed harst grass faster than the quickest man in the village could loose an arrow. The man's family was the most respected of the town," +
        " excepting the Jarl's of course. The Jarl who saw the son's talent as a hunter soon invited him to join his hunting party. They would venture deep into the icy heart of the wild" +
        " bringing back only the finest meats, and taking them with hot plutt berry cider for their dinners. It was after living for a long time like this that the boy started to crave" +
        " guidance from the gods. He had always taken their gifts as having been given freely up until that point. He was not sure why this chasm was splitting deep within his being but" +
        " he knew he had to jump in or else he would never know what really was in store for him.|@The next hunt he went on was when he met her. He gouged his spear deep into the flesh " +
        "of the unbelievably large walrus. She hadn't resisted, in fact it seemed as if she had welcomed it. Lekli's silver hair poured like flowing water from the puncture. When at last" +
        " the walrus seemed to be no more there remained only the frail body of an old woman whose hair seemed to tangle with the moonlight forming shining braids in the night sky."], ["^^@The" +
        " boy stood struck with awe at the godly spectacle that shone before him. This was the lady who his father had spoken of. The wise woman who had tasted the truth. When he came back to himself" +
        " he ran to the frost bitten old lady and collected her up in his strong arms. She was so light, and her breath was chilled. by the time the boy had returned to the village, the woman had been " +
        "completely engulfed in silver light.|@The woman slipped gently from his arms falling to her feet like a leave falls softly ohk-Tarl. There was little difference between the snow she walked on and " +
        "the feet she walked with. She walked until she arrived to the center of town, and there she cried a single tear. Her tear travelled the maze of wrinkles down her cheek finally dropping from her chin " +
        "to the frozen Tarl. The old man hurried to his house and gathered the tied strands of silver hair that he had once pulled from Lekli's head when she was within the fish. He held his hand " +
        "outstretched to her. She took the man by the hand and recollected the tied strands into her own hair, shining even brighter than before. She whispered thanks and a great secret and then planted her roots " +
        "once more. She became a tall pine tree, and resided over her people forever more. She whispered the truth to the farmers as they sowed their grain each"], [ "^^bright, and her windy voice showed the path to the " +
            "juiciest and most nutritious of berries, and her riddles hovering mistily in the air brought luck to the hunters. Her branches reached out towards the sky as if to embrace the gods, and her needles " +
            "pointed and sharp shone reflections of what paths lie ahead for all who might follow. The father, and the son, both sat below the pine and listened. It is said that they heard the secret that Lekli had" +
        " learned from the gods because they stayed under that tree until hunger and thirst claimed them. No amount of urging could convince them to feed the cravings of their own mortality. The moons light sat in their" +
        " eyes and when they finally closed they both drank the stars and swam into the horizon. The hunt for their truth was fullfilled. It is said still that if you listen closely enough to the great pine that grows in the" +
        " center of Paalka, you might hear the Lekli's message. It is also said that the tree carries with it the favor of the Gods, and that those who bring their offerings to that place will be offered a piece of " +
        "the great wisdom. Lekli helped her people in life and still in death helps us all."], ["^@@@@@@Hymn of the North||___________________________________________________________________________" +
        "_______________________________________________||@@-- Tarl-Shetv, Sheth-Shehl, Du-Gron Nosetv Hhun-Dohkehl --|`Frosty land and a sea of cold, it's hard but we endure`|@@-- Hhun-Shan Jath Grun Gehr Kehr Tvel --|`We have been here, " +
        "durable and stubborn, for a long time` |@@-- Hhun-Rotv Klath-Ruhn Thee Tvet Thel--|`We live and hunt strong then and now`|@@-- Hhun-Shan-Toor, Hhun-Hhokel --|`We are content, and we improve ourselves`|@@-- Tvuhm Ashan Joohr " +
        "Mel --|`Because we don't exist without alcohol`"], [" "]];
    }
    else if (itemType == "madmanNote")
    {
        reading = [["@^^^||All i hear is the buetyful music, i reckon its as sweet as a Songberd. See can I the mist surround me blu and course i can touch it as if me blanket back at me home. Something be stalking me  i reckon she's a " +
        "right nasty one but i know that nothing can be kind in this world so i mite as well axsept it. Love is a fikle thing but true love like this aint. she's calling to me, so i might well be right to answer the call. "]];
    }
    else if (itemType == "lonersJournal")
    {
        reading = [["@@@^^|| Day 1: ||||**I should have enough provisions to make it to Lethik. I even bought a sword from Svehn. He told me that it would be wise to hire mercenary escorts, Baaahh!! Mercenaries are costly, and its a waste of money if you ask me."], ["@@@^^|| Day 2: ||||**I saw a tasty looking ardil on the side of the road. I chased it into the tall grass, but when I finally caught up to it it was limp and dead in the mouth of a frich. The beasty eyed me real good like it wanted to eat me too. Not a chance that'd happen cause I had brought my sword. I swung at the beasty but it was a fast one and I was only able to give it a little cut before it ran away. I chopped away some grass and set my tent up after that. I have to save energy if I want to cross The Crags tomorrow."], ["@@@^^|| Day 3: ||||**I got bit on the ankle, I think it's infected, cause it burns something bad. What happened is - in the morning I heard a shuffling outside my tent and so I grabbed my sword and went outside to confront whatever was there. Well there was a whole pack of friches waiting for me, somthing like a-hundred of em' or somthing like that. I fought them all off, but one of the beasties got me ankle real bad."], ["@@@^^|| Day 4: ||||** I went back to Teshir today to get meself some bandages for me ankle. Laandeg told me that'd be best if I didn't travel, he thought I wouldn't make it or something I don't know. But he's wrong. I showed him; I marched right on out of his shop the moment the bandage was good and tightened up. There is no frich in the world that can make me back down from my goal."], ["@@@^^|| Day 5: ||||**The hills here are real steep. I was climbing one and I almost fell right backwards to the ground cause the rock I was holding fell the moment I had moved my hand. The friches here are bigger than I expected, I guess I just didn't believe the tales of the giant black friches. Thought they were to scare the kids, nothing more. I hope that I don't find any berulns out here, those were always the scariest from the stories. Fierce beasts that'l eat whatever they can get their teeth around, and they're good climbers. But, the only beasties I've seen so far were asleep, by Timuk's beard I'm lucky! It's been raining lately but It looks like it's gonna be clearing up. I think I'll make somthing to eat now before it rains again."]];
    }
    else if (itemType == "ultherRIP")
    {
        reading = [["@@@^ Here Lies Ulther the Brave ||* May he hunt, drink and sing in the great valley of Halmthafgh for the rest of time. ||When the first of the freydic first settled this once unfamilar southern land they were confronted by wild beasts and primitive and vile hyelings that dominated the land. Ulther himself slayed over fifty hyelings and was responsible for the disbandment of the largest encampment of them. Ulther's might was matched by many others who also brought glory to their people in High King Thigislul's name, may he rest in the eternal glory of Halmthafgh under the watchful eye of Gemesh with his most admired predecessors. However, ulther did not become the brave through might alone, no, he proved himself to be the most valorous of his comrades in arms when he confronted the most fearsome of beasts. The great bear of the Wuncwer Woods savaged all that would challenge it. The great bear attacked the once so well established hamlet of Diiruhhlat where Ulther and his family and many of his fellows took their bread and mead each day. The warriors who had braved the savage hyelings ran at the sight of the ferocious towering black furred beast. They were torn asunder and dragged effortlessly into its awful maw. Ulther though was brave, he grabbed a torch and knocked over the hamlet's several pots of oil in somber anticipation. He died that day, but not by the bear's terrible claws nor by its terrible teeth, but by fire; the very same fires that engulfed his adversary. It is supposed that the bear was a test of the will of the freydic people and that because of Ulther the Brave, the wise and powerful Gemeth knew we were truly a great people, destined for the frosted valleys of Halmthafgh. The massive flaming beast was absorbed into the land, and envolped into the darkness of the earth not to threaten the worthy people of the Isles of Freynor ever again."]];
    }
    else if (itemType == "stolenTabletLetter")
    {
        reading = [["^|Dear Niilo, ||If you are the one who opened the envelope that held this letter it is already too late to save your life. I cursed it so as to kill you for cheating me, 'twas nothing personal, as I'm sure your error was made in ignorance. The tablet you stole was not a spell, I'll have you know, rather some useless stories about a freydic god, and some nonsense about how he favored your people. It was all written in old freydic. |I blame myself too, I should have looked at the tablet more closely to verify its authenticity before paying you so lavishly for it. I disposed of it like the garbage it was, as a slight to your bogus religion I hid it away in an abandoned mineshaft guarded by a swarm of basilisks that I summoned. Die knowing that your last relevant act in life was to steal an ancient part of your people's religious history for a measely 900 coins. ||Yours truely, High Magus Aleksi of the Cephrian council"]];
    }
    else if (itemType == "estolProof")
    {
        reading = [["^|Lo, the boss needs you to get him this new spell we stole as soon as possible. You can't let anybody else in on our boss's secret, alright. If anybody asks, this scroll is just a secret code, or something like that. Oh and I left you some more kolum powder to sell, keep up the good work!"]];
    }
}